version: "3"
services:
  backend:
    build: ./backend
    container_name: app_backend
    #network_mode: 'host'
    #ports:
    #- "5000:5000"
    environment:
      #DATABASE_URL: "mysql://docker-app-db:wnsgh!23@docker-app-db.c8hr0qxqzkg2.ap-northeast-2.rds.amazonaws.com:3306/docker-app"
      #DATABASE_URL: "mysql://junho:wnsgh!23@127.0.0.1:3306/docker-app"
      DATABASE_URL: "mysql://root:braun5271!@localhost:3306/docker-app"
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: braun5271!
      MYSQL_DATABASE: docker_app
      MYSQL_PORT: 3306
  frontend:
    build: ./frontend
    container_name: app_frontend
    #ports:
    #  - "3000:3000"
    stdin_open: true
  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3000:80"
  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: app_mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      DATABASE_URL: "mysql://root:braun5271!@localhost:3306/docker-app"
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: braun5271!
      MYSQL_DATABASE: docker_app
      MYSQL_PORT: 3306
    extra_hosts:
      - "host.docker.internal:host-gateway"
  #nginx: 
  #  restart: always
  #  image: junho/docker-nginx
  #  ports:
  #    - "80:80"

  
