version: "3"
services:
  backend:
    build: ./backend
    container_name: app_backend
    ports:
    - "5000:5000"
    environment:
      - DATABASE_URL="mysql://junho:braun5271!@localhost:3306/dockerfirstmyapp"
  frontend:
    build: ./frontend
    container_name: app_frontend
    stdin_open: true
  nginx: 
    restart: always
    image: junho/docker-nginx
    ports:
      - "80:80"

  
