version: "3"
services:
  backend:
    #image: wnsgh5049/visitor_book_backend
    build: ./backend
    container_name: app_backend
  frontend:
    #image: wnsgh5049/visitor_book_frontend
    build: ./frontend
    container_name: app_frontend
  nginx: 
    #image: wnsgh5049/visitor_book_nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3000:80"