FROM node:14.14.0-alpine

WORKDIR /app

COPY ./package.json ./
COPY prisma ./prisma/
ENV DATABASE_URL=mysql://root:braun5271!@localhost:8080/dockerfirstmyapp
RUN npm install
RUN npx prisma
#RUN npx prisma init
RUN npx prisma db pull
RUN npx prisma generate

COPY . .

EXPOSE 5000

CMD ["npm", "start"]

